# Conor Weir, ID: 23418374 - Operating Systems Project 1 - Custom Shell
# csc1021/customshell

customshell: ./src/customshell.c ./src/utility.c ./src/shell_commands.c ./src/customshell.h ./src/shell_commands.h
	gcc -Wall ./src/customshell.c ./src/utility.c ./src/shell_commands.c -o ./bin/customshell
