# STUDENT NAME: CONOR WEIR
# STUDENT ID: 23418374
# ACADEMIC INTEGRITY STATEMENT: I acknowledge DCU's academic integrity policy.
# csc1021/customshell

customshell: ./src/customshell.c ./src/utility.c ./src/shell_commands.c ./src/customshell.h ./src/shell_commands.h
	gcc -Wall ./src/customshell.c ./src/utility.c ./src/shell_commands.c -o ./bin/customshell
